### ISSUE TITLE
Add a share button on the site

### ISSUE THREAD

**Issue by ramantehlan** [ramantehlan/Moi#2]
People might want to have a feature, where they would like their site to be shared on social media sites.

**Comment by nverma12345** [comment]
[Social media buttons.zip](https://github.com/ramantehlan/Moi/files/2970174/Social.media.buttons.zip)

Extract The zip file use Html and Css code in body 
Pass-nishant123

**Comment by ramantehlan** [comment]
Hey @nverma12345,
This looks promising, I appreciate your efforts. But here is how it could be better. Those social media share buttons need to be placed under the about section when clicked, they must share the site to their respective platforms.  

Here is a prototype, which works quite well. https://ramantehlan.github.io/Moi/
